// <auto-generated />
using System;
using Letstudy.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Letstudy.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260411152540_BoardsAccessKeysList")]
    partial class BoardsAccessKeysList
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Letstudy.Models.AccessKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActivated")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.HasIndex("StudentId");

                    b.ToTable("access_keys");
                });

            modelBuilder.Entity("Letstudy.Models.Board", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TutorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("TutorId");

                    b.ToTable("boards");
                });

            modelBuilder.Entity("Letstudy.Models.Module", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.ToTable("modules");
                });

            modelBuilder.Entity("Letstudy.Models.ModuleItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uuid");

                    b.Property<int>("ModuleType")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.ToTable("module_items");
                });

            modelBuilder.Entity("Letstudy.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("users");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("StudentTutor", b =>
                {
                    b.Property<Guid>("StudentsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TutorsId")
                        .HasColumnType("uuid");

                    b.HasKey("StudentsId", "TutorsId");

                    b.HasIndex("TutorsId");

                    b.ToTable("StudentTutor");
                });

            modelBuilder.Entity("Letstudy.Models.Student", b =>
                {
                    b.HasBaseType("Letstudy.Models.User");

                    b.ToTable("students");
                });

            modelBuilder.Entity("Letstudy.Models.Tutor", b =>
                {
                    b.HasBaseType("Letstudy.Models.User");

                    b.ToTable("tutors");
                });

            modelBuilder.Entity("Letstudy.Models.AccessKey", b =>
                {
                    b.HasOne("Letstudy.Models.Board", "Board")
                        .WithMany("AccessKeys")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Letstudy.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId");

                    b.Navigation("Board");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Letstudy.Models.Board", b =>
                {
                    b.HasOne("Letstudy.Models.Student", null)
                        .WithMany("Boards")
                        .HasForeignKey("StudentId");

                    b.HasOne("Letstudy.Models.Tutor", "Tutor")
                        .WithMany("Boards")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("Letstudy.Models.Module", b =>
                {
                    b.HasOne("Letstudy.Models.Board", "Board")
                        .WithMany("Modules")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");
                });

            modelBuilder.Entity("Letstudy.Models.ModuleItem", b =>
                {
                    b.HasOne("Letstudy.Models.Module", "Module")
                        .WithMany("Items")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("StudentTutor", b =>
                {
                    b.HasOne("Letstudy.Models.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Letstudy.Models.Tutor", null)
                        .WithMany()
                        .HasForeignKey("TutorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Letstudy.Models.Student", b =>
                {
                    b.HasOne("Letstudy.Models.User", null)
                        .WithOne()
                        .HasForeignKey("Letstudy.Models.Student", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Letstudy.Models.Tutor", b =>
                {
                    b.HasOne("Letstudy.Models.User", null)
                        .WithOne()
                        .HasForeignKey("Letstudy.Models.Tutor", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Letstudy.Models.Board", b =>
                {
                    b.Navigation("AccessKeys");

                    b.Navigation("Modules");
                });

            modelBuilder.Entity("Letstudy.Models.Module", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Letstudy.Models.Student", b =>
                {
                    b.Navigation("Boards");
                });

            modelBuilder.Entity("Letstudy.Models.Tutor", b =>
                {
                    b.Navigation("Boards");
                });
#pragma warning restore 612, 618
        }
    }
}
