services:
#  letstudy:
#    image: letstudy
#    build:
#      context: .
#      dockerfile: Letstudy/Dockerfile
#  
  db:
    image: postgres:16-alpine
    container_name: letstudy-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: belik3002
      POSTGRES_DB: LetstudyDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
volumes:
  postgres_data: